[git]
upstreamRemote = "upstream"
upstreamBranch = "main"
forkRemote = "origin"
targetBranch = "main"
patchPrefix = "patch/"

[fetch]
allowFetch = false
fetchTags = true
prune = true
pruneTags = false

[safety]
allowRebuild = false
allowCapture = false
allowPull = false
