name: check

on:
  push:
    branches:
      - main
  pull_request:
  workflow_dispatch:

jobs:
  check:
    runs-on: bun
    steps:
      - uses: actions/checkout@v4
      - name: Install
        run: bun install --frozen-lockfile
      - name: Typecheck
        run: bun run check:types
      - name: Test
        run: bun run test
      - name: Build docs
        run: bun run docs:build
      - name: Build container
        run: |
          apt-get update
          apt-get install -y docker.io
          docker build -t patch:ci .
